name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest

    - name: Run tests
      run: cargo llvm-cov nextest --cobertura --output-path coverage.xml --profile ci

    - name: Create test report
      uses: test-summary/action@v2
      if: always()
      with:
        paths: "target/nextest/ci/junit.xml"
        output: test-summary.md

    - name: Create coverage report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        output: file
        format: markdown

    - name: Upload test XML
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: junit-test-results
        path: 'target/nextest/ci/junit.xml'
        retention-days: 1

    - name: Upload coverage XML
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-results
        path: 'coverage.xml'
        retention-days: 1

    - name: Add reports to job summary
      run: |
        echo -e "### Test Results\n\n" >> $GITHUB_STEP_SUMMARY
        cat test-summary.md >> $GITHUB_STEP_SUMMARY
        echo -e "\n\n### Coverage Results\n\n" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
